// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBitCEfuYzyu6tFNIFnhwXWkFuqa2BhXiQ',
    appId: '1:619769580202:web:389416c6a0b522955f1ed3',
    messagingSenderId: '619769580202',
    projectId: 'dbecoinnova-92ea5',
    authDomain: 'dbecoinnova-92ea5.firebaseapp.com',
    storageBucket: 'dbecoinnova-92ea5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbWOykmCeR1zA8lzG1e41aDby2sVjExME',
    appId: '1:619769580202:android:a28f2f3dda5669b35f1ed3',
    messagingSenderId: '619769580202',
    projectId: 'dbecoinnova-92ea5',
    storageBucket: 'dbecoinnova-92ea5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdv64A0Zl9Y2BsFCTZ7JMexZctYoBytLs',
    appId: '1:619769580202:ios:32e2515b1ba0f5df5f1ed3',
    messagingSenderId: '619769580202',
    projectId: 'dbecoinnova-92ea5',
    storageBucket: 'dbecoinnova-92ea5.appspot.com',
    iosBundleId: 'com.example.ecoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdv64A0Zl9Y2BsFCTZ7JMexZctYoBytLs',
    appId: '1:619769580202:ios:2ad9a96872c1032d5f1ed3',
    messagingSenderId: '619769580202',
    projectId: 'dbecoinnova-92ea5',
    storageBucket: 'dbecoinnova-92ea5.appspot.com',
    iosBundleId: 'com.example.ecoapp.RunnerTests',
  );
}
